#!/usr/bin/env bash
# install.sh — Install the data-to-chart skill.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_NAME="data-to-chart"
GLOBAL_SKILL_DIR="${HOME}/.claude/skills/${SKILL_NAME}"
BIN_DIR="${XDG_BIN_HOME:-${HOME}/.local/bin}"
WRAPPER_PATH="${BIN_DIR}/${SKILL_NAME}"
PROJECT_SKILL_DIR="${SCRIPT_DIR}/.claude/skills/${SKILL_NAME}"

MODE="global"

for arg in "$@"; do
  case "$arg" in
    --project) MODE="project" ;;
    -h|--help)
      cat <<EOF
Usage: $0 [--project]
  (default)   Install globally to ~/.claude/skills/${SKILL_NAME}
  --project   Install only into ./.claude/skills/${SKILL_NAME}.
EOF
      exit 0 ;;
    *) echo "Unknown argument: $arg" >&2; exit 1 ;;
  esac
done

info()  { printf '  %s\n' "$*"; }
warn()  { printf '  ! %s\n' "$*" >&2; }
error() { printf '  x %s\n' "$*" >&2; exit 1; }

require_file() { [[ -f "$1" ]] || error "Missing required file: $1"; }

check_python() {
  if ! command -v python >/dev/null 2>&1 && ! command -v python >/dev/null 2>&1; then
    warn "python not found on PATH. Install Python 3.10+ before using the skill."
    return 0
  fi
  local py
  if command -v python >/dev/null 2>&1; then py="python"; else py="python"; fi
  local ver major minor
  ver="$($py -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')"
  major="${ver%%.*}"; minor="${ver##*.}"
  info "Python: ${ver} (${py})"
  if (( major < 3 )) || { (( major == 3 )) && (( minor < 10 )); }; then
    warn "Python 3.10+ required; found ${ver}."
  fi
  return 0
}

check_plotly() {
  local py
  if command -v python >/dev/null 2>&1; then py="python"
  elif command -v python >/dev/null 2>&1; then py="python"
  else return 0; fi
  if $py -c 'import plotly' >/dev/null 2>&1; then
    info "Plotly: installed"
  else
    warn "Plotly not found. Install dependencies with:"
    warn "    $py -m pip install -r \"${SCRIPT_DIR}/requirements.txt\""
  fi
  return 0
}

check_path() {
  case ":${PATH}:" in
    *":${BIN_DIR}:"*) info "PATH: ${BIN_DIR} is already on PATH" ;;
    *)
      warn "${BIN_DIR} is NOT on your PATH."
      warn "Add this line to your ~/.bashrc or ~/.zshrc:"
      warn "    export PATH=\"${BIN_DIR}:\$PATH\""
      warn "Then restart your terminal." ;;
  esac
}

copy_bundle() {
  local dest="$1"
  require_file "${SCRIPT_DIR}/SKILL.md"
  require_file "${SCRIPT_DIR}/render_chart.py"
  require_file "${SCRIPT_DIR}/requirements.txt"
  mkdir -p "${dest}"
  cp "${SCRIPT_DIR}/SKILL.md"         "${dest}/SKILL.md"
  cp "${SCRIPT_DIR}/render_chart.py"  "${dest}/render_chart.py"
  cp "${SCRIPT_DIR}/requirements.txt" "${dest}/requirements.txt"
  if [[ -d "${SCRIPT_DIR}/examples" ]]; then
    rm -rf "${dest}/examples"
    cp -r "${SCRIPT_DIR}/examples" "${dest}/examples"
  fi
}

install_global() {
  echo "Installing ${SKILL_NAME} (global)..."
  copy_bundle "${GLOBAL_SKILL_DIR}"
  info "Skill installed: ${GLOBAL_SKILL_DIR}"
  mkdir -p "${BIN_DIR}"
  cat > "${WRAPPER_PATH}" <<EOF
#!/usr/bin/env bash
# Auto-generated by data-to-chart install.sh — do not edit.
exec python "${GLOBAL_SKILL_DIR}/render_chart.py" "\$@"
EOF
  chmod +x "${WRAPPER_PATH}"
  info "Wrapper installed: ${WRAPPER_PATH}"
}

install_project() {
  echo "Installing ${SKILL_NAME} (project-local)..."
  copy_bundle "${PROJECT_SKILL_DIR}"
  info "Skill installed: ${PROJECT_SKILL_DIR}"
}

check_python
check_plotly

if [[ "${MODE}" == "project" ]]; then
  install_project
  echo; echo "Done. (project-local — no wrapper installed)"
else
  install_global
  echo; check_path; echo
  echo "Done."; echo
  echo "Next steps:"
  echo "  1. If '${BIN_DIR}' is not on your PATH, add it (see above)."
  echo "  2. Restart your terminal."
  echo "  3. Try: ${SKILL_NAME} --input examples/bar.json --output chart.html"
fi